<?php
//Include the necessary scripts
	$essentials->requireLogin();
	$essentials->setTitle("Sell Your Books");
	$essentials->includePluginClass("display/Course");
	$essentials->includePluginClass("display/Sell_Book_Display");
	$essentials->includePluginClass("processing/Sell_Book_Process");
	$essentials->includeJS("//tinymce.cachefly.net/4/tinymce.min.js");
	$essentials->includeJS("sell.superpackage.min.js");
	$essentials->includeCSS("sell.superpackage.min.css");
	
//Instantiate form element display class
	$params = $essentials->params ? $essentials->params[0] : 0;
	$userID = $essentials->user->ID;
	$successRedirect = $essentials->friendlyURL("");
	$failRedirect = $essentials->friendlyURL("sell-books");
	$display = new FFI\BE\Sell_Book_Display($params, $userID, $failRedirect);

//Instantiate the form processor class
	new FFI\BE\Sell_Book_Process($params);
	
//Display the page
	echo "<h1>Sell Your Books</h1>
	
<form class=\"form-horizontal\" method=\"post\">
";

//Display the splash section
	$esaterEggBkg = $essentials->user->ID == 198 ? " style=\"background-image:url(" . $essentials->normalizeURL("styles/backgrounds/beans.jpg") . ")\"" : "";
	$easterEggTitle = $essentials->user->ID == 198 ? "Oh my Beans!" : "Sell Your Books"; //For a friend :-)

	echo "<section id=\"splash\">
<div class=\"ad-container\"" . $esaterEggBkg . ">
<div class=\"ad-contents\">
<h2>" . $easterEggTitle . "</h2>
</div>
</div>
</section>

";
	
//Display the directions
	echo "<section class=\"welcome\">
<h2>Sell Your Books</h2>
<p>If you are interested in selling your book to another student, use this page to post your book. If an individual finds your posting, he or she will be in touch with you to purchase this book.</p>
</section>

";

//Display the book information section
	echo "<section class=\"information step stripe\">
<header>
<h2>Book Information</h2>
<h3>We'll need to know a little bit about the book you are selling.</h3>
<h4 class=\"step\">1</h4>
</header>

<div class=\"control-group\">
<label class=\"control-label\" for=\"ISBN10\">ISBN-10:</label>
<div class=\"controls\">
" . $display->getISBN10() . "
<span class=\"searching\" id=\"searching10\"></span>
</div>
</div>

<div class=\"control-group\">
<label class=\"control-label\" for=\"ISBN13\">ISBN-13:</label>
<div class=\"controls\">
" . $display->getISBN13() . "
<span class=\"searching\" id=\"searching13\"></span>
</div>
</div>

<div class=\"control-group\">
<label class=\"control-label\" for=\"title\">Title:</label>
<div class=\"controls\">
" . $display->getTitle() . "
</div>
</div>

<div class=\"control-group\">
<label class=\"control-label\" for=\"author\">Author(s):</label>
<div class=\"controls\">
" . $display->getAuthors() . "
</div>
</div>

<div class=\"control-group\">
<label class=\"control-label\" for=\"edition\">Edition:</label>
<div class=\"controls\">
" . $display->getEdition() . "
</div>
</div>
</section>

";

//Display the book cover section
	echo "<section class=\"cover step\">
<header>
<h2>Book Cover</h2>
<h3>We'll need to know what the cover of the book looks like. Don't worry, we'll do our best to help you find the right one!</h3>
<h4 class=\"step\">2</h4>
</header>

" . $display->getCover() . "
</section>

";

//Display the book classes section
	$allCourses = FFI\BE\Course::getCourses();
	$courses = "";
	
	foreach ($allCourses as $course) {
		$courses .= "<option value=\"" . $course->Code . "\">" . $course->Name . "</option>
";
	}

	echo "<section class=\"dependent step stripe\">
<header>
<h2>Dependent Courses</h2>
<h3>In which classes did you use this book? Don't bother researching all of the classes which use this book, just tell us the ones where you used it.</h3>
<h4 class=\"step\">3</h4>
</header>

<div id=\"course-template\">
<select name=\"copy\">
<option value=\"\">- Select Course -</option>
" . $courses . "
</select>
</div>

<div id=\"suggestions\"></div>

<div class=\"table-wrapper\">
" . $display->getCourses() . "
</div>

<span class=\"add-course\">Add Course</span>
</section>

";

//Display the book information generated by the user section
	echo "<section class=\"remaining step\">
<header>
<h2>The Rest is Up to You</h2>
<h3>We just don't feel as though we've been fully acquainted with your book, yet.</h3>
<h4 class=\"step\">4</h4>
</header>

<div class=\"control-group\">
<label class=\"control-label\" for=\"price\">Price:</label>
<div class=\"controls\">
<div class=\"input-prepend input-append\">
<span class=\"add-on\">\$</span>
" . $display->getPrice() . "
<span class=\"add-on\">.00</span>
</div>
</div>
</div>

<div class=\"control-group\">
<label class=\"control-label\" for=\"condition\">Condition:</label>
<div class=\"controls\">
" . $display->getCondition() . "
</div>
</div>

<div class=\"control-group\">
<label class=\"control-label\" for=\"writing\">Writing or markings:</label>
<div class=\"controls\">
" . $display->getWriting() . "
</div>
</div>
</section>

";

//Display the comments section
	echo "<section class=\"comments step stripe\">
<header>
<h2>Closing Thoughts (Optional)</h2>
<h3>Is there anything you'd like to share with your potential buyers?</h3>
<h4 class=\"step\">5</h4>
</header>

<div class=\"control-group\">
<label class=\"control-label\">Comments:</label>
<div class=\"controls\">
" . $display->getComments() . "
</div>
</div>
</section>

";

//Display the submit button
	echo "<section class=\"no-border step stripe\">
<button class=\"btn btn-primary\" type=\"submit\">Submit Book</button>
<button class=\"btn cancel\" type=\"button\">Cancel</button>
</section>
</form>";
?>
